language: php

php:
  - 5.5
  - 5.4

before_script:
  - composer install --dev

addons:
  code_climate:
    repo_token: 781c51ddaa271006924740db7f1a02bbdf1c7345fce93d609ba98097822715d0

after_script:
  after_script:
  - CODECLIMATE_REPO_TOKEN="781c51ddaa271006924740db7f1a02bbdf1c7345fce93d609ba98097822715d0" bin/test-reporter --stdout > codeclimate.json
  - curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports